import type {CompanyFinancialData,FinancialPeriod,FinancialValue,MarketCompany} from '@/lib/markets/types';

type JsonRecord=Record<string,unknown>;
const API='https://www.alphavantage.co/query';
const SOURCE='Alpha Vantage';
const CACHE_SECONDS=21600;

function num(value:unknown):number|undefined{if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'&&value.trim()&&value!=='None'&&value!=='null'){const n=Number(value.replace(/,/g,''));return Number.isFinite(n)?n:undefined;}return undefined;}
function rows(value:unknown):JsonRecord[]{return Array.isArray(value)?value.filter(x=>x&&typeof x==='object') as JsonRecord[]:[];}
function latest(rowsValue:unknown):JsonRecord|undefined{return rows(rowsValue).sort((a,b)=>String(b.fiscalDateEnding??'').localeCompare(String(a.fiscalDateEnding??'')))[0];}
function fv(value:unknown,period?:string,type?:'annual'|'quarterly'|'ttm',currency?:string,methodology:'provider'|'calculated'='provider'):FinancialValue|undefined{const n=num(value);return n===undefined?undefined:{value:n,period,periodType:type,currency,source:SOURCE,retrievedAt:new Date().toISOString(),methodology};}
function empty(error?:string):CompanyFinancialData{return {valuation:{},incomeStatement:{},profitability:{},balanceSheet:{},cashFlow:{},shareholder:{},periods:[],capabilities:{quote:false,historicalPrices:false,valuation:false,incomeStatement:false,balanceSheet:false,cashFlow:false,dividends:false},source:SOURCE,retrievedAt:new Date().toISOString(),error};}
async function getJson(url:string):Promise<JsonRecord>{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'iStocks/1.0'},next:{revalidate:CACHE_SECONDS}} as RequestInit & {next?:{revalidate:number}});if(!r.ok)throw new Error(`${SOURCE} returned HTTP ${r.status}`);return await r.json() as JsonRecord;}
async function call(functionName:string,symbol:string):Promise<JsonRecord>{const key=process.env.ALPHA_VANTAGE_API_KEY;if(!key)throw new Error('ALPHA_VANTAGE_API_KEY is not configured');const url=new URL(API);url.searchParams.set('function',functionName);url.searchParams.set('symbol',symbol);url.searchParams.set('apikey',key);return getJson(url.toString());}
function errorFrom(data:JsonRecord):string|undefined{return typeof data.Note==='string'?data.Note:typeof data['Error Message']==='string'?data['Error Message']:typeof data.Information==='string'?data.Information:undefined;}
function statementPeriods(income:JsonRecord):FinancialPeriod[]{const annual=rows(income.annualReports).map(x=>String(x.fiscalDateEnding??'')).filter(Boolean).map(date=>{const d=new Date(date);return {label:`FY ${d.getUTCFullYear()}`,periodType:'annual' as const,endDate:date,fiscalYear:d.getUTCFullYear()};});const quarterly=rows(income.quarterlyReports).map(x=>String(x.fiscalDateEnding??'')).filter(Boolean).map(date=>{const d=new Date(date);return {label:`Q${Math.floor(d.getUTCMonth()/3)+1} ${d.getUTCFullYear()}`,periodType:'quarterly' as const,endDate:date,fiscalYear:d.getUTCFullYear(),quarter:Math.floor(d.getUTCMonth()/3)+1};});return [...annual,...quarterly].sort((a,b)=>(b.endDate??'').localeCompare(a.endDate??''));}
function sumLatestFour(value:unknown,field:string):number|undefined{const values=rows(value).sort((a,b)=>String(b.fiscalDateEnding??'').localeCompare(String(a.fiscalDateEnding??''))).slice(0,4).map(x=>num(x[field])).filter((x):x is number=>x!==undefined);return values.length===4?values.reduce((a,b)=>a+b,0):undefined;}

export async function getAlphaVantageCompanyFundamentals(company:MarketCompany):Promise<CompanyFinancialData|undefined>{
  if(!process.env.ALPHA_VANTAGE_API_KEY)return undefined;
  const symbol=(company.ticker).trim().toUpperCase();
  try{
    const overview=await call('OVERVIEW',symbol);const overviewError=errorFrom(overview);if(overviewError)return empty(overviewError);
    const [income,balance,cash]=await Promise.all([call('INCOME_STATEMENT',symbol),call('BALANCE_SHEET',symbol),call('CASH_FLOW',symbol)]);
    const statementError=errorFrom(income)||errorFrom(balance)||errorFrom(cash);if(statementError)return empty(statementError);
    const annualIncome=rows(income.annualReports);const quarterlyIncome=rows(income.quarterlyReports);const latestIncome=latest(quarterlyIncome)??latest(annualIncome);const latestBalance=latest(balance.quarterlyReports)??latest(balance.annualReports);const latestCash=latest(cash.quarterlyReports)??latest(cash.annualReports);
    const currency=String(overview.Currency??company.currency??'');
    const revenue=sumLatestFour(quarterlyIncome,'totalRevenue')??num(latestIncome?.totalRevenue)??num(overview.RevenueTTM);const grossProfit=sumLatestFour(quarterlyIncome,'grossProfit')??num(latestIncome?.grossProfit)??num(overview.GrossProfitTTM);const operatingIncome=sumLatestFour(quarterlyIncome,'operatingIncome')??num(latestIncome?.operatingIncome);const ebitda=sumLatestFour(quarterlyIncome,'ebitda')??num(latestIncome?.ebitda)??num(overview.EBITDA);const netIncome=sumLatestFour(quarterlyIncome,'netIncome')??num(latestIncome?.netIncome)??num(overview.ProfitLoss);const eps=num(overview.EPS);const assets=num(latestBalance?.totalAssets);const liabilities=num(latestBalance?.totalLiabilities);const equity=num(latestBalance?.totalShareholderEquity);const cashValue=num(latestBalance?.cashAndCashEquivalentsAtCarryingValue)??num(latestBalance?.cashAndShortTermInvestments);const longDebt=num(latestBalance?.longTermDebtNoncurrent);const shortDebt=num(latestBalance?.shortTermDebt);const totalDebt=longDebt!==undefined||shortDebt!==undefined?(longDebt??0)+(shortDebt??0):undefined;const ocf=sumLatestFour(cash.quarterlyReports,'operatingCashflow')??num(latestCash?.operatingCashflow);const capex=sumLatestFour(cash.quarterlyReports,'capitalExpenditures')??num(latestCash?.capitalExpenditures);const fcf=ocf!==undefined&&capex!==undefined?ocf+capex:undefined;const shares=num(overview.SharesOutstanding);const dividendPerShare=num(overview.DividendPerShare);const dividendYield=num(overview.DividendYield);const payout=num(overview.PayoutRatio);const pe=num(overview.PERatio);const ps=num(overview.PriceToSalesRatioTTM);const pb=num(overview.PriceToBookRatio);const evRevenue=num(overview.EVToRevenue);const evEbitda=num(overview.EVToEBITDA);const marketCap=num(overview.MarketCapitalization);const roe=num(overview.ReturnOnEquityTTM);const roa=num(overview.ReturnOnAssetsTTM);const enterpriseValue=marketCap!==undefined&&totalDebt!==undefined&&cashValue!==undefined?marketCap+totalDebt-cashValue:undefined;const netDebt=totalDebt!==undefined&&cashValue!==undefined?totalDebt-cashValue:undefined;const bookValuePerShare=shares!==undefined&&shares!==0&&equity!==undefined?equity/shares:undefined;const revenueGrowth=num(overview.QuarterlyRevenueGrowthYOY);const grossMargin=revenue&&grossProfit!==undefined?grossProfit/revenue:undefined;const operatingMargin=revenue&&operatingIncome!==undefined?operatingIncome/revenue:undefined;const netMargin=revenue&&netIncome!==undefined?netIncome/revenue:undefined;const fcfMargin=revenue&&fcf!==undefined?fcf/revenue:undefined;
    const periods=statementPeriods(income);const capabilities={quote:false,historicalPrices:false,valuation:[pe,ps,pb,evRevenue,evEbitda,marketCap].some(x=>x!==undefined),incomeStatement:[revenue,grossProfit,operatingIncome,ebitda,netIncome,eps].some(x=>x!==undefined),balanceSheet:[cashValue,totalDebt,netDebt,assets,liabilities,equity].some(x=>x!==undefined),cashFlow:[ocf,capex,fcf].some(x=>x!==undefined),dividends:[dividendPerShare,dividendYield,payout].some(x=>x!==undefined)};
    return {valuation:{pe:fv(pe,'TTM','ttm'),ps:fv(ps,'TTM','ttm'),pb:fv(pb,'MRQ','quarterly'),evRevenue:fv(evRevenue,'TTM','ttm'),evEbitda:fv(evEbitda,'TTM','ttm'),enterpriseValue:fv(enterpriseValue,'MRQ','quarterly',currency,'calculated')},incomeStatement:{revenue:fv(revenue,'TTM','ttm',currency),revenueGrowth:fv(revenueGrowth,'TTM','ttm'),grossProfit:fv(grossProfit,'TTM','ttm',currency),operatingIncome:fv(operatingIncome,'TTM','ttm',currency),ebitda:fv(ebitda,'TTM','ttm',currency),netIncome:fv(netIncome,'TTM','ttm',currency),eps:fv(eps,'TTM','ttm',currency),grossMargin:fv(grossMargin,'TTM','ttm'),operatingMargin:fv(operatingMargin,'TTM','ttm'),netMargin:fv(netMargin,'TTM','ttm')},profitability:{roe:fv(roe,'TTM','ttm'),roa:fv(roa,'TTM','ttm')},balanceSheet:{cash:fv(cashValue,'MRQ','quarterly',currency),totalDebt:fv(totalDebt,'MRQ','quarterly',currency),netDebt:fv(netDebt,'MRQ','quarterly',currency,'calculated'),totalAssets:fv(assets,'MRQ','quarterly',currency),totalLiabilities:fv(liabilities,'MRQ','quarterly',currency),equity:fv(equity,'MRQ','quarterly',currency),bookValue:fv(equity,'MRQ','quarterly',currency),bookValuePerShare:fv(bookValuePerShare,'MRQ','quarterly',currency,'calculated')},cashFlow:{operatingCashFlow:fv(ocf,'TTM','ttm',currency),capitalExpenditure:fv(capex,'TTM','ttm',currency),freeCashFlow:fv(fcf,'TTM','ttm',currency,'calculated'),fcfMargin:fv(fcfMargin,'TTM','ttm',undefined,'calculated')},shareholder:{sharesOutstanding:fv(shares,'MRQ','quarterly'),dividendPerShare:fv(dividendPerShare,'TTM','ttm',currency),dividendYield:fv(dividendYield,'TTM','ttm'),payoutRatio:fv(payout,'TTM','ttm')},periods,capabilities,source:SOURCE,retrievedAt:new Date().toISOString(),error:capabilities.incomeStatement||capabilities.balanceSheet||capabilities.cashFlow?undefined:`No usable Alpha Vantage fundamentals returned for ${symbol}.`};
  }catch(error){return empty(error instanceof Error?error.message:'Unknown Alpha Vantage fundamentals error');}
}
